eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      allow-override: false

management:
  tracing:
    sampling:
      probability: 1.0